quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    reactive:
      name: quarkus
      url: postgresql://localhost:5432/postgres
      max-size: 10
      initial-size: 10